export const URL_PRODUCTS = "http://localhost:3001/products/";
export const URL_PRODUCTS_QUERY = "http://localhost:3001/products?name=";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_NAME_PRODUCTS = "GET_NAME_PRODUCTS";
export const GET_BRAND = "GET_BRAND";
export const FILTER_PRICES = "FILTER_PRICES";
export const FILTER_CATEGORIES = "FILTER_CATEGORIES";
export const FILTER_GENDER = "FILTER_GENDER";
export const FILTER_SIZE = "FILTER_SIZE";
export const ORDER_BY_NAME = "ORDER_BY_NAME";
export const ORDER_BY_PRICE = "ORDER_BY_PRICES";
export const GET_DETAILS = "GET_DETAILS";
export const CLEAR_DETAILS = "CLEAR_DETAILS";
export const POST_REVIEW = "POST_REVIEW";
export const DELETE_OWN_REVIEW = "DELETE_OWN_REVIEW";
export const EDIT_OWN_REVIEW = "EDIT_OWN_REVIEW";

export const POST_PRODUCT = "POST_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const EDIT_PRODUCT = "EDIT PRODUCT";
export const DELETE_REVIEW = "DELETE_REVIEW";
export const ACTION_DE_PRUEBA = "ACTION_DE_PRUEBA";
